# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J_0XSaJvPZ4DuICCNx0lLuW4rt7Ay1GD
"""

import math

def calculate_circle_properties(radius):
    # 計算圓周長
    circumference = 2 * math.pi * radius

    # 計算圓面積
    area = math.pi * radius**2

    return circumference, area

# 提示使用者輸入半徑
radius = float(input("請輸入圓的半徑："))

# 呼叫函式計算圓周長和圓面積
circumference, area = calculate_circle_properties(radius)

# 顯示結果
print(f"圓周長: {circumference:.2f}")
print(f"圓面積: {area:.2f}")

# 收集用戶的個人資料
user_name = input("請輸入您的姓名：")
user_age = int(input("請輸入您的年齡："))
user_height = float(input("請輸入您的身高（米）："))
favorite_color = input("請輸入您喜愛的顏色：")

# 將資料存儲在字典中
user_data = {
    "姓名": user_name,
    "年齡": user_age,
    "身高": user_height,
    "喜愛的顏色": favorite_color
}

# 格式化個人資料摘要
summary = f"{user_data['姓名']}, {user_data['年齡']}歲, 身高{user_data['身高']}米, 喜愛的顏色是{user_data['喜愛的顏色']}。"

# 輸出個人資料摘要
print(summary)

# 提示使用者輸入整數
user_input = input("請輸入一個整數：")

# 將輸入轉換為整數
try:
    number = int(user_input)
    # 判斷是否為偶數
    if number % 2 == 0:
        print(f"{number} 是偶數。")
    else:
        print(f"{number} 不是偶數。")
except ValueError:
    print("請輸入有效的整數。")